name: RACR
description: development of RACR for NCDP
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
#init
dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.0.1
  flutter_mobx: ^1.0.1
  provider: ^4.0.2
  shared_preferences: ^0.5.6+1
  sembast: ^2.1.3
  expandable: ^4.1.2
  percent_indicator: ^2.1.1+1
  chewie: ^0.9.8+1
  path_provider: ^1.6.0
  permission_handler: ^4.2.0+hotfix.3
  flutter_downloader: ^1.4.1
  url_launcher: ^5.4.2
  font_awesome_flutter: ^8.7.0
  flutter_markdown: ^0.3.4
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^1.0.1



flutter:
  

  uses-material-design: true
