/// Flutter icons IrjLogoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IrjLogoIcons
///      fonts:
///       - asset: fonts/IrjLogoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IrjLogoIcons {
  IrjLogoIcons._();

  static const _kFontFam = 'IrjLogoIcons';
  static const _kFontPkg = null;

  static const IconData irjlogowhite = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData irglogo= IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
